version: "3.7"
volumes:
    pgdata:
        driver: local
services:
  db:
    image: postgres:14
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./data_source/sql/install.sql:/docker-entrypoint-initdb.d/install.sql
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=dash
      - POSTGRES_PASSWORD=dash
      - POSTGRES_DB=dash
      - POSTGRES_INITDB_ARGS="-E utf8"
    shm_size: 8192MB
    security_opt:
      - seccomp:unconfined
  ds_server:
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./data_source/Dockerfile
    image: ds_server
    volumes:
      - /Users/sergejnovozilov/PycharmProjects/dash_sample/logs/:/var/log/dash_app
    restart: always
    security_opt:
      - seccomp:unconfined
  dash:
    depends_on:
      - ds_server
    ports:
      - "8050:8050"
    build:
      context: .
      dockerfile: ./dash_app/Dockerfile
    image: dash
    volumes:
      - /Users/sergejnovozilov/PycharmProjects/dash_sample/logs/:/var/log/dash_app
    restart: always
    security_opt:
      - seccomp:unconfined